sonar.projectKey=sofyaandrade_auditoria-sistemas-sdd
sonar.organization=sofyaandrade
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**
sonar.python.version=3.12
