sonar.projectKey=SUBSTITUA_PELO_PROJECT_KEY
sonar.organization=SUBSTITUA_PELA_ORGANIZATION
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**
sonar.python.version=3.12
